Add iteration support for touchpads
adafruit/Adafruit_CircuitPython_CircuitPlayground pull request #113
Opened 2022-02-01 02:38 UTC by tekktrik

Addresses issue #103 as follows:

1. Adds `touched` property for showing list of of pin names currently registering a touch
2. Adds `touchpads` property got showing list of pin names that are set up as touchpad inputs
3. Continues to allow inputs to only be initialized as `touchio.TouchIn` as needed
4. Now allows for touchpads to be initialized and deinitialized as touchpad inputs, which allows those pins to be used for other things if wanted!
5. Existing methods for checking touchpads still works!
6. Modifies/adds examples to demonstrate new functionality

This is all powered by the new `IterableInput` class, which should remain hidden from the user but provides the above functionalities.

2022-02-17 17:12 UTC, kattni requested changes
My concern here is increasing the size of the library. We need to make sure it still fits frozen in CircuitPython for the CPX before considering merging this.

2022-02-17 17:15 UTC, tekktrik commented
Sounds good, I can look at removing anything not immediately needed as well.  If any of the above functionalities aren't needed, let me know an I can try and factor them out.  Also, if there's a good way to test this library as frozen.

2022-02-17 17:16 UTC, kattni commented
@tekktrik There absolutely is a way to test it! That's the next step before trying to slim down the code. Do you know how to build CircuitPython? Testing a frozen library is pretty simple once you have a CircuitPython build environment set up.

2022-02-17 17:18 UTC, tekktrik commented
No, I don't actually, I think I've seen guides though, is there a Learn guide for it?

2022-02-17 17:19 UTC, kattni commented
Yep! It's [here](https://learn.adafruit.com/building-circuitpython/build-circuitpython). Please message me on Discord if you need assistance. Once you have the build environment working, I'll show you how to test the frozen library.

2022-02-17 22:23 UTC, tekktrik commented
So it builds, and it currently doesn't look like I have too much in the way of "unused" code.  So I think it really depends on what functionalities are worth introducing and just cutting the rest:

1. `touched` property for showing pin names (`str`) currently **registering touch**
2. `touchpads` shows the pins names (`str`) that are currently **setup as touch inputs**
3. It only initializes touch inputs as needed, similar to how it's been done before this
4. You can init and deinit touchpads.  This seemed like a big want, but I don't know the balance of freezing this into the firmware vs trying to recover the pins as touchpads or saving RAM
5. You can access pins by both pin names (`str`) and pin numbers (`int`)

Let me know what to cutout!

2022-02-17 22:28 UTC, tekktrik commented
Also, it may make sense to hide this class in the documentation, let me know if I should exclude it in `api.rst`

2022-02-18 20:10 UTC, tekktrik commented on adafruit_circuitplayground/circuit_playground_base.py
> +            if value not in range(1, 7):
Oh neat, I didn't think about that, thanks!

2022-02-18 20:10 UTC, tekktrik commented
Thanks for reviewing!  Let me take a stab at this, but I may end up just creating a new branch for this if it makes more sense to start from scratch :)

2022-02-18 20:12 UTC, kattni commented
@tekktrik Starting a new PR is perfectly fine. Simply make sure you reference this PR in the new PR notes so there's some continuity there. You can leave this open until you create the new one, if you like.

2022-02-18 21:44 UTC, closed without merging